<?php

namespace DataHelm\Crawler\Dom;

/**
 * Helpers for turning DOM elements into stable CSS selectors and structural
 * "signatures" (used to recognise repeating list rows).
 */
final class Selector
{
    /**
     * @return list<string>
     */
    public static function classes(\DOMElement $el): array
    {
        $class = trim($el->getAttribute('class'));

        if ($class === '') {
            return [];
        }

        return array_values(array_filter(preg_split('/\s+/', $class) ?: []));
    }

    /**
     * A structural fingerprint (tag + classes) used to group sibling elements
     * that look like repetitions of the same template.
     */
    public static function signature(\DOMElement $el): string
    {
        $classes = self::classes($el);

        return strtolower($el->tagName) . ($classes ? '.' . implode('.', $classes) : '');
    }

    /**
     * Best-effort CSS selector for a single element, preferring an id, then
     * classes, and falling back to the bare tag name. Unsafe identifiers
     * (Tailwind-style classes with special characters) are skipped, as are
     * auto-generated per-record ids (see {@see looksAutoGenerated()}) which
     * only ever match one element and so are useless for repeating lists.
     */
    public static function cssFor(\DOMElement $el): string
    {
        $tag = strtolower($el->tagName);

        $id = trim($el->getAttribute('id'));
        if ($id !== '' && self::isCleanIdentifier($id) && ! self::looksAutoGenerated($id)) {
            return $tag . '#' . $id;
        }

        $css = $tag;
        foreach (self::classes($el) as $class) {
            if (self::isCleanIdentifier($class)) {
                $css .= '.' . $class;
            }
        }

        return $css;
    }

    private static function isCleanIdentifier(string $value): bool
    {
        return (bool) preg_match('/^[A-Za-z_-][A-Za-z0-9_-]*$/', $value);
    }

    /**
     * True for ids that look auto-generated / per-record — e.g. "offer-4750824",
     * "post_18342", "item-99". A run of two or more digits almost always marks a
     * database id that is unique to one element, which makes it worthless as a
     * selector for a repeating list (it would match a single item).
     */
    private static function looksAutoGenerated(string $id): bool
    {
        return (bool) preg_match('/\d{2,}/', $id);
    }
}
